backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "writing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "post.njk",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["post"],
          hint: "First tag should always be 'post'",
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "data"
    label: "Site Data"
    files:
      - label: "Site Information"
        name: "site"
        file: "_data/site.json"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Website URL", name: "url", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }

      - label: "Experience"
        name: "experience"
        file: "_data/experience.json"
        fields:
          - label: "Experience Items"
            name: "experience"
            widget: "list"
            fields:
              - { label: "Job Title", name: "title", widget: "string" }
              - { label: "Company", name: "company", widget: "string" }
              - { label: "Period", name: "period", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Projects"
        name: "projects"
        file: "_data/projects.json"
        fields:
          - label: "Project Items"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "URL", name: "url", widget: "string" }
              - {
                  label: "Type",
                  name: "type",
                  widget: "select",
                  options:
                    [
                      "article",
                      "presentation",
                      "podcast",
                      "video",
                      "talk",
                      "project",
                    ],
                }

      - label: "Homepage Content"
        name: "homepage"
        file: "_data/homepage.json"
        fields:
          - {
              label: "Profile Image URL",
              name: "profileImage",
              widget: "string",
            }
          - { label: "Intro Paragraph 1", name: "intro1", widget: "text" }
          - { label: "Intro Paragraph 2", name: "intro2", widget: "text" }
          - { label: "Intro Paragraph 3", name: "intro3", widget: "text" }
          - {
              label: "Belief Statement",
              name: "beliefStatement",
              widget: "text",
            }
          - {
              label: "Belief Description",
              name: "beliefDescription",
              widget: "text",
            }
          - {
              label: "Expertise Title",
              name: "expertiseTitle",
              widget: "string",
            }
          - {
              label: "Expertise Subtitle",
              name: "expertiseSubtitle",
              widget: "string",
            }
          - {
              label: "Personal Section Title",
              name: "personalTitle",
              widget: "string",
            }
          - { label: "Personal Intro", name: "personalIntro", widget: "text" }
          - label: "Personal Items"
            name: "personalItems"
            widget: "list"
            fields:
              - { label: "Item", name: "item", widget: "text" }
          - label: "Expertise Areas"
            name: "expertiseAreas"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Experience Page"
        name: "experiencePage"
        file: "_data/experiencePage.json"
        fields:
          - { label: "Page Subtitle", name: "subtitle", widget: "text" }
          - label: "Jobs"
            name: "jobs"
            widget: "list"
            fields:
              - { label: "Job Title", name: "title", widget: "string" }
              - { label: "Company", name: "company", widget: "string" }
              - {
                  label: "Company URL",
                  name: "companyUrl",
                  widget: "string",
                  required: false,
                }
              - { label: "Period", name: "period", widget: "string" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - label: "Key Achievements"
                name: "achievements"
                widget: "list"
                required: false
                fields:
                  - { label: "Achievement", name: "item", widget: "text" }
              - label: "Skills"
                name: "skills"
                widget: "list"
                required: false
                fields:
                  - { label: "Skill", name: "skill", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.njk"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "framer-base.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Permalink",
              name: "permalink",
              widget: "hidden",
              default: "/about/",
            }
          - { label: "Body", name: "body", widget: "markdown" }
